/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GerencialPrin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;
import Metodos.*;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
/**
 *
 * @author Yasser Velasquez
 */
public class Base1 extends javax.swing.JFrame {
DefaultTableModel modelo=new DefaultTableModel();
DirectoO nuevo=new DirectoO();
AbsorbenteO nuevo1=new AbsorbenteO();
/*CDirecto cdi=new CDirecto();
CAbsorbente cab=new CAbsorbente();*/
gerencialprin gp;
    /**
     * Creates new form Base1
     */
    public Base1() {
        
        initComponents();
        String [] temp={"0","0","0","0","0","0"};
        modelo.addColumn("ITO");
        modelo.addColumn("CTO");
        modelo.addColumn("CVT");
        modelo.addColumn("Q");
        modelo.addColumn("CVU");
        modelo.addColumn("PVU");
        modelo.addRow(temp);
        jTable1.setModel(modelo);
        this.setSize(860,860);
        jTabbedPane1.setSize(this.getSize());
        Total_V.setEnabled(false);
        jScrollPane1.setSize(this.getSize().width-10,this.getSize().height);
        jPanel1.setSize(this.getSize());
        Fondo.setIcon(MYimage("gerencial2.png",this.getSize().width,this.getSize().height));
        Fondo.setSize(this.getSize());
        Directo.setEnabled(false);
        MetodoAbsorbente.setEnabled(false);
    }
    
    ImageIcon MYimage(String nombre,int wt ,int ht){
        ImageIcon icon=new ImageIcon(getClass().getResource(nombre));
        Image icon2= icon.getImage();
        ImageIcon icono3=new ImageIcon(icon2.getScaledInstance(wt, ht, Image.SCALE_DEFAULT));
        return icono3;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PrecioV = new javax.swing.JTextField();
        Total_V = new javax.swing.JTextField();
        UndsV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Inv_P = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Inv_I = new javax.swing.JTextField();
        Inv_F = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        gastos_de_Administracion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Cost_F_P = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cost_F_P_u = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Costo_V_P = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Cost_V_P_u = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        gasto_v_de_venta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Gastos_financieros = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Otros_gastos = new javax.swing.JTextField();
        Otros_productos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Add_row = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        set_row = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        set_CVU = new javax.swing.JTextField();
        set_PVU = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        set_CFT = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Directo = new javax.swing.JRadioButtonMenuItem();
        Absorbente = new javax.swing.JMenu();
        MetodoAbsorbente = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        jLabel1.setText("Precio de Venta");

        jLabel2.setText("Unidades Vendidas");

        jLabel3.setText("Total=");

        PrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioVActionPerformed(evt);
            }
        });
        PrecioV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioVKeyTyped(evt);
            }
        });

        Total_V.setEditable(false);
        Total_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_VActionPerformed(evt);
            }
        });

        UndsV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UndsVKeyTyped(evt);
            }
        });

        jLabel4.setText("Costo de Articulo Manufacturado");

        Inv_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inv_PActionPerformed(evt);
            }
        });
        Inv_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Inv_PKeyTyped(evt);
            }
        });

        jLabel5.setText("Unidades Producidas");

        jLabel7.setText("Inventario Inicial");

        Inv_I.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Inv_IKeyTyped(evt);
            }
        });

        Inv_F.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Inv_FKeyTyped(evt);
            }
        });

        jLabel10.setText("Inventario Final");

        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Gastos de Ventas y Administracion");

        gastos_de_Administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastos_de_AdministracionActionPerformed(evt);
            }
        });
        gastos_de_Administracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gastos_de_AdministracionKeyTyped(evt);
            }
        });

        jLabel6.setText("Costo Fijo de Produccion");

        Cost_F_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cost_F_PKeyTyped(evt);
            }
        });

        jLabel8.setText("Costo Fijo de Produccion Unitario");

        Cost_F_P_u.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cost_F_P_uKeyTyped(evt);
            }
        });

        jLabel9.setText("Costo Variable de Produccion");

        Costo_V_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Costo_V_PKeyTyped(evt);
            }
        });

        jLabel12.setText("Costo Variable de Produccion Unitario");

        Cost_V_P_u.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cost_V_P_uKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Gasto Variable de Venta");

        gasto_v_de_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gasto_v_de_ventaKeyTyped(evt);
            }
        });

        jLabel14.setText("Gastos Financieros");

        Gastos_financieros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Gastos_financierosKeyTyped(evt);
            }
        });

        jLabel15.setText("Otros Gastos");

        Otros_gastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Otros_gastosKeyTyped(evt);
            }
        });

        Otros_productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Otros_productosKeyTyped(evt);
            }
        });

        jLabel16.setText("Otros Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(UndsV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total_V, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Inv_P, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(Inv_I, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inv_F))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cost_F_P)
                    .addComponent(Costo_V_P, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cost_F_P_u)
                    .addComponent(Cost_V_P_u, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(151, 151, 151))
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Otros_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gastos_de_Administracion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(gasto_v_de_venta)
                                    .addComponent(Gastos_financieros)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Otros_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(UndsV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Total_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inv_I, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jCheckBox3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Inv_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(Inv_F, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cost_F_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Cost_F_P_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Costo_V_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Cost_V_P_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(gasto_v_de_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(gastos_de_Administracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Gastos_financieros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Otros_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Otros_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(65, 65, 65))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Metodos de Costeo", jScrollPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Agregar una fila");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Add_row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Add_rowKeyTyped(evt);
            }
        });

        jButton3.setText("Agregar n Filas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Establecer n Filas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        set_row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                set_rowKeyTyped(evt);
            }
        });

        jButton5.setText("Establecer \"CVU\"");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Establecer \"PVU\"");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Establecer \"CFT\"");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(set_CFT, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(set_PVU)
                            .addComponent(Add_row)
                            .addComponent(set_row)
                            .addComponent(set_CVU))))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(set_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(set_CVU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(set_PVU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(set_CFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Analisis de C.V.U", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 100, 100);
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 0, 0);

        jMenu1.setText("Login");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Principal/Salir");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("C. Directo");

        Directo.setSelected(true);
        Directo.setText("Metodo Directo o Variable");
        Directo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectoActionPerformed(evt);
            }
        });
        jMenu2.add(Directo);

        jMenuBar1.add(jMenu2);

        Absorbente.setText("C. Absorbente");

        MetodoAbsorbente.setSelected(true);
        MetodoAbsorbente.setText("Metodo Absorbente o Natural");
        MetodoAbsorbente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetodoAbsorbenteActionPerformed(evt);
            }
        });
        Absorbente.add(MetodoAbsorbente);

        jMenuBar1.add(Absorbente);

        jMenu3.setText("Punto De Equilibrio");

        jMenuItem1.setText("Grafica de punto de Equilibrio");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MetodoAbsorbenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetodoAbsorbenteActionPerformed
  //   cab.setVisible(true);
        nuevo1.setAbsorbenteC1();
    }//GEN-LAST:event_MetodoAbsorbenteActionPerformed

    private void DirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectoActionPerformed
        nuevo.CDirectoO();
       // cdi.setVisible(true);
    }//GEN-LAST:event_DirectoActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        gp=new gerencialprin();
        gp.setVisible(true);
       // CDirectoC nuevo=new CDirectoC();
    }//GEN-LAST:event_formWindowClosed

    private void PrecioVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioVKeyTyped
        // TODO add your handling code here:
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PrecioVKeyTyped

    private void PrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioVActionPerformed

    private void Inv_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inv_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inv_PActionPerformed

    private void Inv_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Inv_PKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Inv_PKeyTyped

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel1.setSize(this.getSize());
        jTabbedPane1.setSize(this.getSize());
        jScrollPane1.setSize(this.getSize().width-10,this.getSize().height-60);
        jSeparator1.setSize(this.getSize().width, 5);
        jSeparator2.setSize(this.getSize().width, 5);
        jSeparator3.setSize(this.getSize().width, 5);
        jSeparator4.setSize(this.getSize().width, 5);
        jPanel1.setSize(this.getSize());
        Fondo.setIcon(MYimage("gerencial2.png",this.getSize().width,this.getSize().height));
        Fondo.setSize(this.getSize());
    }//GEN-LAST:event_formComponentResized

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
       if(!Inv_F.isEnabled())
      {Inv_F.setEnabled(true);}
      else{
              Inv_F.setEnabled(false);
          }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void Total_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_VActionPerformed

    private void UndsVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UndsVKeyTyped
        // TODO add your handling code here:
        char cuentita=evt.getKeyChar();
        if(cuentita<'0'||cuentita>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_UndsVKeyTyped

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
        if(!Inv_I.isEnabled())
      {Inv_I.setEnabled(true);}
      else{
              Inv_I.setEnabled(false);
          }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        Cost_F_P.setEnabled(true);
        Cost_F_P_u.setEnabled(false);
        Cost_F_P_u.setText("0");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        Cost_F_P.setEnabled(false);
        Cost_F_P_u.setEnabled(true);
        Cost_F_P.setText("0");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        
        Costo_V_P.setEnabled(true);
        Cost_V_P_u.setEnabled(false);
        Cost_V_P_u.setText("0");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        Costo_V_P.setEnabled(false);
        Cost_V_P_u.setEnabled(true);
        Costo_V_P.setText("0");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        
        if(Vacio(PrecioV)&&Vacio(UndsV)&&Vacio(Inv_I)
         &&Vacio(Inv_F)&&Vacio(Inv_P)&&Vacio(Cost_F_P)
         &&Vacio(Cost_F_P_u)&&Vacio(Costo_V_P)&&Vacio(Cost_V_P_u)
         &&Vacio(gasto_v_de_venta)&&Vacio(gastos_de_Administracion)&&Vacio(Gastos_financieros)
         &&Vacio(Otros_gastos)&&Vacio(Otros_productos))
       {/*****************Directo******************************/
           nuevo.setVentas(Integer.parseInt(UndsV.getText()), Double.parseDouble(PrecioV.getText()));           
           nuevo.setINV(Integer.parseInt(Inv_I.getText()), Integer.parseInt(Inv_F.getText()),Integer.parseInt(Inv_P.getText()));          
           nuevo.setCOSTOS(Double.parseDouble(Cost_F_P.getText()),Double.parseDouble(Costo_V_P.getText())
                   ,Double.parseDouble(Cost_F_P_u.getText()),Double.parseDouble(Cost_V_P_u.getText()));
           nuevo.setCostodeVVariable();
           nuevo.setCostodeVFijo();
           nuevo.setUtilidad();
          /* nuevo.setGastos(Double.parseDouble(Gastos_financieros.getText()), Double.parseDouble(gasto_v_de_venta.getText()),
                           Double.parseDouble(gastos_de_Administracion.getText()),Double.parseDouble(Otros_gastos.getText()),
                           Double.parseDouble(Otros_productos.getText()));*/
          /*****************Absorbente******************************/
          nuevo1.setVentas(Integer.parseInt(UndsV.getText()), Double.parseDouble(PrecioV.getText()));
           
           nuevo1.setINV(Integer.parseInt(Inv_I.getText()), Integer.parseInt(Inv_F.getText()),Integer.parseInt(Inv_P.getText()));
           
           nuevo1.setCOSTOS(Double.parseDouble(Cost_F_P.getText()),Double.parseDouble(Costo_V_P.getText())
                   ,Double.parseDouble(Cost_F_P_u.getText()),Double.parseDouble(Cost_V_P_u.getText()));
           
           nuevo1.setCostodeVVariable();
           
          
           nuevo1.setGastos(Double.parseDouble(Gastos_financieros.getText()), Double.parseDouble(gasto_v_de_venta.getText()),
                           Double.parseDouble(gastos_de_Administracion.getText()),Double.parseDouble(Otros_gastos.getText()),
                           Double.parseDouble(Otros_productos.getText()));
          /***********************************************/
           Directo.setEnabled(true);
           MetodoAbsorbente.setEnabled(true);
           
       }
        else{JOptionPane.showMessageDialog(null,"al parecer usted posee un campo de infomacion vacio,\n por favor aquellos que no tiene opcion de estar inactivos(inv inicial,inv Final ),\n se recomienda y se le pide por etica que introduzca el valor 0","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
        
            
            
           
        
       // CDirectoC h=new CDirectoC();
      //  CAbsorebenteC cab=new CAbsorebenteC();
        //String temp=String.valueOf(h.VentasN());
        //Total_V.setText(temp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gastos_de_AdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastos_de_AdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastos_de_AdministracionActionPerformed

    private void Costo_V_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Costo_V_PKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_Costo_V_PKeyTyped

    private void Cost_F_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cost_F_PKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Cost_F_PKeyTyped

    private void Cost_F_P_uKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cost_F_P_uKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Cost_F_P_uKeyTyped

    private void Cost_V_P_uKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cost_V_P_uKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Cost_V_P_uKeyTyped

    private void gastos_de_AdministracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gastos_de_AdministracionKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_gastos_de_AdministracionKeyTyped

    private void Inv_FKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Inv_FKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Inv_FKeyTyped

    private void Inv_IKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Inv_IKeyTyped
        // TODO add your handling code here:
         char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Inv_IKeyTyped

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
        {Inv_I.setText("0");
        Inv_I.setEnabled(false);}
        else{
        Inv_I.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       if(jCheckBox2.isSelected())
        {Inv_F.setText("0");
        Inv_F.setEnabled(false);}
        else{
        Inv_F.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void gasto_v_de_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gasto_v_de_ventaKeyTyped
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_gasto_v_de_ventaKeyTyped

    private void Gastos_financierosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Gastos_financierosKeyTyped
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Gastos_financierosKeyTyped

    private void Otros_gastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Otros_gastosKeyTyped
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Otros_gastosKeyTyped

    private void Otros_productosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Otros_productosKeyTyped
       char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Otros_productosKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String [] temp={"0","0","0","0","0","0"};
        modelo.addRow(temp);
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(Vacio(Add_row)){int i=Integer.parseInt(Add_row.getText());
        for(int n=0;n<i;n++){
        String [] temp={"0","0","0","0","0","0"};
        modelo.addRow(temp);
        }
        jTable1.setModel(modelo);}
       else{JOptionPane.showMessageDialog(null,"No tiene datos para definir el tamaño de 'n' ","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(Vacio(set_row)){int i=Integer.parseInt(set_row.getText());
        //System.out.println("modelo = "+modelo.getRowCount()+"-------- standar= "+(i-2));
        try{
       while(modelo.getRowCount()!=i-1) {
             modelo.removeRow(0);
            }
            } catch (Exception e) {
            /*JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");*/}
       //System.out.println("modelo = "+modelo.getRowCount()+"-------- standar= "+(i-2));
    try {
        Thread.sleep(200);
    } catch (InterruptedException ex) {
        Logger.getLogger(Base1.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        for(int n=0;n<i;n++){
        String [] temp={"0","0","0","0","0","0"};
        modelo.addRow(temp);
        }
        jTable1.setModel(modelo);}
       else{JOptionPane.showMessageDialog(null,"No tiene datos para definir el tamaño de 'n' ","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void set_rowKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_set_rowKeyTyped
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_set_rowKeyTyped

    private void Add_rowKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Add_rowKeyTyped
        char cuentita=evt.getKeyChar();
        if(cuentita!=','&&(cuentita<'0'||cuentita>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Add_rowKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(Vacio(set_CVU)){
        }
        else{JOptionPane.showMessageDialog(null,"No tiene datos para definir el tamaño de 'n' ","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if(Vacio(set_PVU)){
        }
        else{JOptionPane.showMessageDialog(null,"No tiene datos para definir el tamaño de 'n' ","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(Vacio(set_CFT)){
        }
        else{JOptionPane.showMessageDialog(null,"No tiene datos para definir el tamaño de 'n' ","Campo de informacion vacio",JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Absorbente;
    private javax.swing.JTextField Add_row;
    public static javax.swing.JTextField Cost_F_P;
    public static javax.swing.JTextField Cost_F_P_u;
    public static javax.swing.JTextField Cost_V_P_u;
    public static javax.swing.JTextField Costo_V_P;
    private javax.swing.JRadioButtonMenuItem Directo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField Gastos_financieros;
    public static javax.swing.JTextField Inv_F;
    public static javax.swing.JTextField Inv_I;
    public static javax.swing.JTextField Inv_P;
    private javax.swing.JRadioButtonMenuItem MetodoAbsorbente;
    private javax.swing.JTextField Otros_gastos;
    private javax.swing.JTextField Otros_productos;
    public static javax.swing.JTextField PrecioV;
    public static javax.swing.JTextField Total_V;
    public static javax.swing.JTextField UndsV;
    public static javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField gasto_v_de_venta;
    public static javax.swing.JTextField gastos_de_Administracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField set_CFT;
    private javax.swing.JTextField set_CVU;
    private javax.swing.JTextField set_PVU;
    private javax.swing.JTextField set_row;
    // End of variables declaration//GEN-END:variables
   
    
    public boolean Vacio(JTextField prueba){
            if(prueba.getText().length()<=0){
                return false;
            }
            else {
                return true;
            }
    }
    
    
    public boolean Vacio1(JRadioButton prueba){
            if(prueba.getText().length()<=0){
                return false;
            }
            else {
                return true;
            }
    }
    public static JRadioButton getSelection(ButtonGroup group) 
{
        for (Enumeration e=group.getElements(); e.hasMoreElements(); ) 
        {
            JRadioButton b = (JRadioButton)e.nextElement();
            if (b.getModel() == group.getSelection()) 
            {
                return b;
            }
        }

        return null;
}

}
